# -*- mode: python ; coding: utf-8 -*-
# HearGlass.spec — Single-file PyInstaller build
# =====================================================
# Produces:  dist\HearGlass.exe  (one double-click, no folder needed)
#
# Build:
#   .\venv\Scripts\pyinstaller HearGlass.spec --noconfirm
#
# Notes:
#   • console=False  → no black terminal window appears on launch
#   • onefile=True   → everything packed into a single .exe
#   • UPX is disabled — it frequently corrupts ctranslate2/torch DLLs

from PyInstaller.utils.hooks import collect_data_files, collect_all, copy_metadata

# ── Gather data / binaries / hidden imports for heavy deps ────────────────────
datas     = []
binaries  = []
hiddenimports = []

# faster-whisper + its metadata (needed for importlib.metadata lookups)
datas += collect_data_files('faster_whisper')
datas += copy_metadata('faster-whisper')
datas += copy_metadata('tokenizers')
datas += copy_metadata('huggingface_hub')

# ctranslate2 — the inference backend; collect_all grabs DLLs too
tmp = collect_all('ctranslate2')
datas     += tmp[0]
binaries  += tmp[1]
hiddenimports += tmp[2]

# soundcard — needs the native DLL
tmp = collect_all('soundcard')
datas     += tmp[0]
binaries  += tmp[1]
hiddenimports += tmp[2]

# pycaw — Windows Core Audio bindings
tmp = collect_all('pycaw')
datas     += tmp[0]
binaries  += tmp[1]
hiddenimports += tmp[2]

# comtypes — COM interop used by pycaw
tmp = collect_all('comtypes')
datas     += tmp[0]
binaries  += tmp[1]
hiddenimports += tmp[2]

# torch is no longer needed since VAD runs via onnxruntime


# tokenizers (Rust extension, needs special handling)
tmp = collect_all('tokenizers')
datas     += tmp[0]
binaries  += tmp[1]
hiddenimports += tmp[2]

# pystray + Pillow — system tray icon (gracefully absent at runtime if missing)
try:
    tmp = collect_all('pystray')
    datas += tmp[0]; binaries += tmp[1]; hiddenimports += tmp[2]
except Exception:
    pass
try:
    tmp = collect_all('PIL')
    datas += tmp[0]; binaries += tmp[1]; hiddenimports += tmp[2]
except Exception:
    pass

# ── Extra hidden imports that PyInstaller misses ───────────────────────────────
hiddenimports += [
    # Our own modules
    'transcription_engine',
    'silent_capture',
    # pycaw internals
    'pycaw.pycaw',
    'pycaw.utils',
    # comtypes
    'comtypes.client',
    'comtypes.automation',
    # numpy / scipy helpers
    'numpy.core._multiarray_umath',
    # faster-whisper tokenizer
    'tokenizers',
    # soundcard WASAPI backend
    'soundcard.mediafoundation',
    # Silero VAD no longer needs torch.hub
]

# ── Analysis ──────────────────────────────────────────────────────────────────
a = Analysis(
    ['subtitle_overlay.py'],
    pathex=['.'],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    # Exclude heavy optional packages we definitely don't need
    excludes=[
        'matplotlib', 'pandas', 'scipy', 'sklearn',
        'cv2', 'IPython', 'jupyter',
        'test', 'unittest', 'pyaudio',
        'torch', 'numba', 'pyarrow', 'lxml', 'grpc', 'nltk', 'pydantic', 'torchvision',
    ],
    noarchive=False,
    optimize=0,
)

# ── Filter out PyTorch / torchvision DLLs and other heavy dependencies ────────
def is_excluded(path_str):
    p = path_str.lower()
    return any(k in p for k in ['torch', 'torchvision', 'cublas', 'cusolver', 'cufft', 'cusparse', 'mkl'])

a.binaries = [x for x in a.binaries if not (is_excluded(x[0]) or is_excluded(x[1]))]
a.datas = [x for x in a.datas if not (is_excluded(x[0]) or is_excluded(x[1]))]

pyz = PYZ(a.pure)

# ── Single-file EXE ───────────────────────────────────────────────────────────
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='HearGlass',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,          # UPX off — corrupts ctranslate2 / torch DLLs
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,      # No black terminal window
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    # icon.ico is generated by create_icon.py (run once before building)
    icon='icon.ico',
)
